--[[ Etherbeep - configuration defaults and schema.

	These are the built-in defaults. You normally do not edit this file: the mod
	writes Etherbeep.ini into your Zomboid user folder (next to console.txt, in
	the Lua sub-folder) on first launch, and that file wins over anything here.
]]

Etherbeep = Etherbeep or {}

Etherbeep.MOD_ID = "Etherbeep"
Etherbeep.VERSION = "1.0.0"
Etherbeep.CONFIG_FILE = "Etherbeep.ini"

--- Sounds defined in media/scripts/etherbeep_sounds.txt.
--- Any sound name known to the game works too, including vanilla ones.
Etherbeep.BUNDLED_SOUNDS = {
	"Etherbeep_Chime",
	"Etherbeep_Fanfare",
	"Etherbeep_Blip",
	"Etherbeep_Custom",
}

--- Order matters: it is the order keys are written to Etherbeep.ini.
Etherbeep.SCHEMA = {
	{
		key = "enabled",
		default = true,
		comment = "Master switch. false disables the mod without uninstalling it.",
	},
	{
		key = "sound",
		default = "Etherbeep_Chime",
		comment = "Sound to play. Bundled: Etherbeep_Chime, Etherbeep_Fanfare, Etherbeep_Blip, Etherbeep_Custom.",
	},
	{
		key = "volume",
		default = 0.8,
		min = 0.0,
		max = 1.0,
		comment = "Playback volume, 0.0 to 1.0. Your in-game sound sliders still apply on top of this.",
	},
	{
		key = "delayTicks",
		default = 30,
		min = 0,
		max = 600,
		comment = "Ticks to wait after the character spawns before playing (~60 ticks = 1 second).",
	},
	{
		key = "playOnEveryLoad",
		default = false,
		comment = "true also plays the sound every time you load an existing character, not just brand new ones.",
	},
	{
		key = "debug",
		default = false,
		comment = "true prints what Etherbeep is doing to console.txt.",
	},
}

--- Live settings. Populated by Etherbeep_Settings.lua at game boot.
Etherbeep.settings = {}
for _, entry in ipairs(Etherbeep.SCHEMA) do
	Etherbeep.settings[entry.key] = entry.default
end

function Etherbeep.getSchemaEntry(key)
	for _, entry in ipairs(Etherbeep.SCHEMA) do
		if entry.key == key then
			return entry
		end
	end
	return nil
end

--- Clamp/coerce a value to the type and range declared in the schema.
function Etherbeep.sanitize(key, value)
	local entry = Etherbeep.getSchemaEntry(key)
	if not entry then
		return nil
	end

	local default = entry.default
	if type(default) == "boolean" then
		if type(value) == "boolean" then
			return value
		end
		value = string.lower(tostring(value))
		return value == "true" or value == "1" or value == "yes" or value == "on"
	end

	if type(default) == "number" then
		local number = tonumber(value)
		if not number then
			return default
		end
		if entry.min and number < entry.min then
			number = entry.min
		end
		if entry.max and number > entry.max then
			number = entry.max
		end
		return number
	end

	local text = tostring(value)
	text = string.gsub(text, "^%s*(.-)%s*$", "%1")
	if text == "" then
		return default
	end
	return text
end

function Etherbeep.log(message)
	print("[Etherbeep] " .. tostring(message))
end

function Etherbeep.debug(message)
	if Etherbeep.settings.debug then
		Etherbeep.log(message)
	end
end
